# Name of the Workflow
name: CI
# Triggers
on:
  push:
    branches: [ master ]
# Configure Jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
# Checkout from SCM
      - uses: actions/checkout@v2
        name: Checkout Sources

# Use the workflow template to build and push docker
      - uses: jonyjalfon94/workflow-templates/build-and-push-docker@main
        name: CI
        with:
          lint: true
          test: true
          registry_username: jonyjalfon94
          registry_password: ${{ secrets.DOCKERHUBPASSWORD }}
          image_name: demo-app
          tag: latest
          build_args: |
            FIRST_ARG="Hello"
            SECOND_ARG="World"
            THIRD_ARG="42"
            FOURTH_ARG="foo"
