name: Another CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
    - name: Test and Lint
      uses: jonyjalfon94/workflow-templates/test-and-lint@main
      

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Publish Test Results
        uses: jonyjalfon94/workflow-templates/publish-test-results@main
          
  build:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: jonyjalfon94/workflow-templates/build-and-push-docker-no-tests@main
      name: Build and Push Docker Image
      with:
        registry_username: jonyjalfon94
        registry_password: ${{ secrets.DOCKERHUBPASSWORD }}
        image_name: demo-app
        tag: latest
        build_args: |
          FIRST_ARG="Hello"
          SECOND_ARG="World"

  notify:
    if: always()
    name: Send Slack Notification
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: 'general'
          # For posting a simple plain text message
          slack-message: |-
             GitHub build result: ${{ job.status  }}\n
             Workflow Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\n
             Commit: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}\n
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
