name: Another CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test and Lint
      uses: jonyjalfon94/workflow-templates/test-and-lint@main
      

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Publish Test Results
        uses: jonyjalfon94/workflow-templates/publish-test-results@main
          
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: jonyjalfon94/workflow-templates/build-and-push-docker-no-tests@main
      name: Build and Push Docker Image
      with:
        registry_username: jonyjalfon94
        registry_password: ${{ secrets.DOCKERHUBPASSWORD }}
        image_name: demo-app
        tag: latest
        build_args: |
          FIRST_ARG="Hello"
          SECOND_ARG="World"
