name: Another CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
    
    - name: Get composite run steps repository
      uses: actions/checkout@v2
      with:
        repository: jonyjalfon94/.github
        # Personal access token to check out private repository
        token: ${{ secrets.TOKEN }}
        path: .github

    - name: Test and Lint
      uses: ./.github/actions/test-and-lint

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:

      - name: Get composite run steps repository
        uses: actions/checkout@v2
        with:
          repository: jonyjalfon94/.github
          # Personal access token to check out private repository
          token: ${{ secrets.TOKEN }}
          path: .github

      - name: Publish Test Results
        uses: ./.github/actions/publish-test-results
          
  build:
    if: success() && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: test
    steps:

    - name: Get composite run steps repository
      uses: actions/checkout@v2
      with:
        repository: jonyjalfon94/.github
        # Personal access token to check out private repository
        token: ${{ secrets.TOKEN }}
        path: .github

    - uses: ./.github/actions/build-and-push-docker
      name: Build and Push Docker Image
      with:
        registry_username: jonyjalfon94
        registry_password: ${{ secrets.DOCKERHUBPASSWORD }}
        image_name: demo-app
        tag: latest
        build_args: |
          FIRST_ARG="Hello"
          SECOND_ARG="World"
